version: '3.8'

services:
  api:
    build: .
    container_name: taste_of_heaven_backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - JWT_SECRET=docker_secret_taste_of_heaven_2026
    restart: always
